### ISSUE TITLE
Current bugs

### ISSUE THREAD

**Issue by T-Tanogami** [ryo-ARAKI/Sabra_shell_model#27]
https://github.com/ryo-ARAKI/Sabra_shell_model/blob/aebbc295658a2db76718810f16d24384897b2d02/main.jl#L162-L168
https://github.com/ryo-ARAKI/Sabra_shell_model/blob/aebbc295658a2db76718810f16d24384897b2d02/main.jl#L240-L244
Noise terms are not fixed for the validation branch.

**Comment by ryo-ARAKI** [comment]
@T-Tanogami I cannot thank you enough for your close inspection. I opened several new pull requests to close these issues!
